/**
 * Darwin Core field definitions and vocabularies
 */

// Core Darwin Core terms
export const DARWIN_CORE_TERMS = {
  // Record-level terms
  type: "type",
  modified: "modified",
  language: "language",
  license: "license",
  rightsHolder: "rightsHolder",
  accessRights: "accessRights",
  bibliographicCitation: "bibliographicCitation",
  references: "references",
  institutionID: "institutionID",
  collectionID: "collectionID",
  datasetID: "datasetID",
  institutionCode: "institutionCode",
  collectionCode: "collectionCode",
  datasetName: "datasetName",
  ownerInstitutionCode: "ownerInstitutionCode",
  basisOfRecord: "basisOfRecord",
  informationWithheld: "informationWithheld",
  dataGeneralizations: "dataGeneralizations",
  dynamicProperties: "dynamicProperties",

  // Occurrence terms
  occurrenceID: "occurrenceID",
  catalogNumber: "catalogNumber",
  recordNumber: "recordNumber",
  recordedBy: "recordedBy",
  individualCount: "individualCount",
  organismQuantity: "organismQuantity",
  organismQuantityType: "organismQuantityType",
  sex: "sex",
  lifeStage: "lifeStage",
  reproductiveCondition: "reproductiveCondition",
  behavior: "behavior",
  establishmentMeans: "establishmentMeans",
  occurrenceStatus: "occurrenceStatus",
  preparations: "preparations",
  disposition: "disposition",
  associatedMedia: "associatedMedia",
  associatedReferences: "associatedReferences",
  associatedSequences: "associatedSequences",
  associatedTaxa: "associatedTaxa",
  otherCatalogNumbers: "otherCatalogNumbers",
  occurrenceRemarks: "occurrenceRemarks",

  // Event terms
  eventID: "eventID",
  parentEventID: "parentEventID",
  samplingProtocol: "samplingProtocol",
  sampleSizeValue: "sampleSizeValue",
  sampleSizeUnit: "sampleSizeUnit",
  samplingEffort: "samplingEffort",
  eventDate: "eventDate",
  eventTime: "eventTime",
  startDayOfYear: "startDayOfYear",
  endDayOfYear: "endDayOfYear",
  year: "year",
  month: "month",
  day: "day",
  verbatimEventDate: "verbatimEventDate",
  habitat: "habitat",
  fieldNumber: "fieldNumber",
  fieldNotes: "fieldNotes",
  eventRemarks: "eventRemarks",

  // Location terms
  locationID: "locationID",
  higherGeography: "higherGeography",
  continent: "continent",
  waterBody: "waterBody",
  islandGroup: "islandGroup",
  island: "island",
  country: "country",
  countryCode: "countryCode",
  stateProvince: "stateProvince",
  county: "county",
  municipality: "municipality",
  locality: "locality",
  verbatimLocality: "verbatimLocality",
  minimumElevationInMeters: "minimumElevationInMeters",
  maximumElevationInMeters: "maximumElevationInMeters",
  verbatimElevation: "verbatimElevation",
  minimumDepthInMeters: "minimumDepthInMeters",
  maximumDepthInMeters: "maximumDepthInMeters",
  verbatimDepth: "verbatimDepth",
  minimumDistanceAboveSurfaceInMeters: "minimumDistanceAboveSurfaceInMeters",
  maximumDistanceAboveSurfaceInMeters: "maximumDistanceAboveSurfaceInMeters",
  locationAccordingTo: "locationAccordingTo",
  locationRemarks: "locationRemarks",
  decimalLatitude: "decimalLatitude",
  decimalLongitude: "decimalLongitude",
  geodeticDatum: "geodeticDatum",
  coordinateUncertaintyInMeters: "coordinateUncertaintyInMeters",
  coordinatePrecision: "coordinatePrecision",
  pointRadiusSpatialFit: "pointRadiusSpatialFit",
  verbatimCoordinates: "verbatimCoordinates",
  verbatimLatitude: "verbatimLatitude",
  verbatimLongitude: "verbatimLongitude",
  verbatimCoordinateSystem: "verbatimCoordinateSystem",
  verbatimSRS: "verbatimSRS",
  footprintWKT: "footprintWKT",
  footprintSRS: "footprintSRS",
  footprintSpatialFit: "footprintSpatialFit",
  georeferencedBy: "georeferencedBy",
  georeferencedDate: "georeferencedDate",
  georeferenceProtocol: "georeferenceProtocol",
  georeferenceSources: "georeferenceSources",
  georeferenceVerificationStatus: "georeferenceVerificationStatus",
  georeferenceRemarks: "georeferenceRemarks",

  // Taxonomic terms
  taxonID: "taxonID",
  scientificNameID: "scientificNameID",
  acceptedNameUsageID: "acceptedNameUsageID",
  parentNameUsageID: "parentNameUsageID",
  originalNameUsageID: "originalNameUsageID",
  nameAccordingToID: "nameAccordingToID",
  namePublishedInID: "namePublishedInID",
  taxonConceptID: "taxonConceptID",
  scientificName: "scientificName",
  acceptedNameUsage: "acceptedNameUsage",
  parentNameUsage: "parentNameUsage",
  originalNameUsage: "originalNameUsage",
  nameAccordingTo: "nameAccordingTo",
  namePublishedIn: "namePublishedIn",
  namePublishedInYear: "namePublishedInYear",
  higherClassification: "higherClassification",
  kingdom: "kingdom",
  phylum: "phylum",
  class: "class",
  order: "order",
  family: "family",
  genus: "genus",
  subgenus: "subgenus",
  specificEpithet: "specificEpithet",
  infraspecificEpithet: "infraspecificEpithet",
  taxonRank: "taxonRank",
  verbatimTaxonRank: "verbatimTaxonRank",
  scientificNameAuthorship: "scientificNameAuthorship",
  vernacularName: "vernacularName",
  nomenclaturalCode: "nomenclaturalCode",
  taxonomicStatus: "taxonomicStatus",
  nomenclaturalStatus: "nomenclaturalStatus",
  taxonRemarks: "taxonRemarks",
} as const;

// Standard vocabularies
export const CONTROLLED_VOCABULARIES = {
  sex: ["female", "male", "hermaphrodite", "undetermined"],
  lifeStage: ["adult", "juvenile", "larva", "embryo", "zygote", "egg", "nymph", "pupa"],
  basisOfRecord: [
    "PreservedSpecimen",
    "FossilSpecimen",
    "LivingSpecimen",
    "HumanObservation",
    "MachineObservation",
  ],
  occurrenceStatus: ["present", "absent"],
  establishmentMeans: ["native", "introduced", "naturalised", "invasive", "managed"],
  taxonomicStatus: ["accepted", "synonym", "doubtful", "misapplied"],
  nomenclaturalCode: ["ICZN", "ICN", "ICNCP", "ICNP", "ICTV"],
} as const;
