/**
 * Error codes for consistent error handling across all packages
 */

export enum ErrorCode {
  // General errors
  UNKNOWN_ERROR = "UNKNOWN_ERROR",
  INVALID_INPUT = "INVALID_INPUT",

  // Workspace errors
  WORKSPACE_NOT_FOUND = "WORKSPACE_NOT_FOUND",
  WORKSPACE_ALREADY_EXISTS = "WORKSPACE_ALREADY_EXISTS",
  WORKSPACE_VALIDATION_FAILED = "WORKSPACE_VALIDATION_FAILED",
  WORKSPACE_IO_ERROR = "WORKSPACE_IO_ERROR",

  // Parsing errors
  PARSE_ERROR = "PARSE_ERROR",
  INVALID_FILE_FORMAT = "INVALID_FILE_FORMAT",
  FILE_NOT_FOUND = "FILE_NOT_FOUND",

  // Validation errors
  VALIDATION_FAILED = "VALIDATION_FAILED",
  SCHEMA_VALIDATION_FAILED = "SCHEMA_VALIDATION_FAILED",
  PARTIAL_SUCCESS = "PARTIAL_SUCCESS",

  // Authentication errors
  UNAUTHORIZED = "UNAUTHORIZED",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  TOKEN_EXPIRED = "TOKEN_EXPIRED",

  // Database errors
  DATABASE_ERROR = "DATABASE_ERROR",
  CONNECTION_ERROR = "CONNECTION_ERROR",

  // System warnings and notices
  DEPRECATION_WARNING = "DEPRECATION_WARNING",
}
