// deno-lint-ignore-file no-explicit-any

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root.tsx";
import { Route as VerifyEmailRouteImport } from "./routes/verify-email.tsx";
import { Route as SupportRouteImport } from "./routes/support.tsx";
import { Route as RegisterRouteImport } from "./routes/register.tsx";
import { Route as OldRouteImport } from "./routes/old.tsx";
import { Route as LogoutRouteImport } from "./routes/logout.tsx";
import { Route as LoginRouteImport } from "./routes/login.tsx";
import { Route as IndexRouteImport } from "./routes/index.tsx";
import { Route as ProjectsIndexRouteImport } from "./routes/projects.index.tsx";
import { Route as ProjectsCreateRouteImport } from "./routes/projects.create.tsx";
import { Route as ProjectsProjectIdRouteImport } from "./routes/projects.$projectId.tsx";

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => rootRouteImport,
} as any);
const SupportRoute = SupportRouteImport.update({
  id: "/support",
  path: "/support",
  getParentRoute: () => rootRouteImport,
} as any);
const RegisterRoute = RegisterRouteImport.update({
  id: "/register",
  path: "/register",
  getParentRoute: () => rootRouteImport,
} as any);
const OldRoute = OldRouteImport.update({
  id: "/old",
  path: "/old",
  getParentRoute: () => rootRouteImport,
} as any);
const LogoutRoute = LogoutRouteImport.update({
  id: "/logout",
  path: "/logout",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: "/projects/",
  path: "/projects/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsCreateRoute = ProjectsCreateRouteImport.update({
  id: "/projects/create",
  path: "/projects/create",
  getParentRoute: () => rootRouteImport,
} as any);
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/logout": typeof LogoutRoute;
  "/old": typeof OldRoute;
  "/register": typeof RegisterRoute;
  "/support": typeof SupportRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/projects/create": typeof ProjectsCreateRoute;
  "/projects": typeof ProjectsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/logout": typeof LogoutRoute;
  "/old": typeof OldRoute;
  "/register": typeof RegisterRoute;
  "/support": typeof SupportRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/projects/create": typeof ProjectsCreateRoute;
  "/projects": typeof ProjectsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/logout": typeof LogoutRoute;
  "/old": typeof OldRoute;
  "/register": typeof RegisterRoute;
  "/support": typeof SupportRoute;
  "/verify-email": typeof VerifyEmailRoute;
  "/projects/$projectId": typeof ProjectsProjectIdRoute;
  "/projects/create": typeof ProjectsCreateRoute;
  "/projects/": typeof ProjectsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/logout"
    | "/old"
    | "/register"
    | "/support"
    | "/verify-email"
    | "/projects/$projectId"
    | "/projects/create"
    | "/projects";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/logout"
    | "/old"
    | "/register"
    | "/support"
    | "/verify-email"
    | "/projects/$projectId"
    | "/projects/create"
    | "/projects";
  id:
    | "__root__"
    | "/"
    | "/login"
    | "/logout"
    | "/old"
    | "/register"
    | "/support"
    | "/verify-email"
    | "/projects/$projectId"
    | "/projects/create"
    | "/projects/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  LoginRoute: typeof LoginRoute;
  LogoutRoute: typeof LogoutRoute;
  OldRoute: typeof OldRoute;
  RegisterRoute: typeof RegisterRoute;
  SupportRoute: typeof SupportRoute;
  VerifyEmailRoute: typeof VerifyEmailRoute;
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute;
  ProjectsCreateRoute: typeof ProjectsCreateRoute;
  ProjectsIndexRoute: typeof ProjectsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/verify-email": {
      id: "/verify-email";
      path: "/verify-email";
      fullPath: "/verify-email";
      preLoaderRoute: typeof VerifyEmailRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/support": {
      id: "/support";
      path: "/support";
      fullPath: "/support";
      preLoaderRoute: typeof SupportRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/register": {
      id: "/register";
      path: "/register";
      fullPath: "/register";
      preLoaderRoute: typeof RegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/old": {
      id: "/old";
      path: "/old";
      fullPath: "/old";
      preLoaderRoute: typeof OldRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/logout": {
      id: "/logout";
      path: "/logout";
      fullPath: "/logout";
      preLoaderRoute: typeof LogoutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/": {
      id: "/projects/";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof ProjectsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/create": {
      id: "/projects/create";
      path: "/projects/create";
      fullPath: "/projects/create";
      preLoaderRoute: typeof ProjectsCreateRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof ProjectsProjectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  OldRoute: OldRoute,
  RegisterRoute: RegisterRoute,
  SupportRoute: SupportRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsCreateRoute: ProjectsCreateRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
